### ISSUE TITLE
Repetitive "A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body?" warnings

### ISSUE THREAD

**Issue by d-todor** [growthbook/growthbook-sdk-java#95]
Hi, we are using this library in an android Kotlin project and we have noticed a large number of warnings about a leaked connection:

> 2024-08-05 16:52:47.362 15615-10824 okhttp.OkHttpClient W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:52:47.362 15615-10824 okhttp.OkHttpClient    W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:53:00.852 17877-8976  okhttp.OkHttpClient    W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:53:00.852 17877-8976  okhttp.OkHttpClient    W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:53:00.852 17877-8976  okhttp.OkHttpClient    W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:53:00.853 17877-8976  okhttp.OkHttpClient    W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:53:00.853 17877-8976  okhttp.OkHttpClient     W  A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2024-08-05 16:55:23.777 15615-13975 okhttp.OkHttpClient     A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

Warnings are printed at quite a significant rate as can be seen from the logs above.

Since adding the GrowthBook integration, we also noticed new non-fatal exceptions reported from Firebase RemoteConfig library. At first it looks like something completely unrelated and probably indicating some API calls while there is no network, but for some reason a huge spike is seen that matches the rollout of the versions (staged rollout over several days) which included the GrowthBook integration.
>       Non-fatal Exception: hj.g: Unable to connect to the server. Check your connection and try again.
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.makeRealtimeHttpConnection(ConfigRealtimeHttpClient.java:1)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.retryHttpConnectionWhenBackoffEnds(ConfigRealtimeHttpClient.java:39)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient.beginRealtimeHttpStream(ConfigRealtimeHttpClient.java:38)
       at com.google.firebase.remoteconfig.internal.ConfigRealtimeHttpClient$1.run(ConfigRealtimeHttpClient.java:38)
       at com.google.firebase.concurrent.DelegatingScheduledExecutorService.lambda$schedule$0(DelegatingScheduledExecutorService.java:5)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0(CustomThreadFactory.java:64)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by Bohdan-Kim** [comment]
Hello, @d-todor!
Could you please specify SDK version you are using? Don't see such a logs on my side.

**Comment by gvillo** [comment]
I can confirm the same is happening in JDK 17 using STALE_WHILE_REVALIDATE, library version 0.9.9

```
2024-08-07T23:12:37.438-03:00  WARN 55516 --- [ ConnectionPool] okhttp3.OkHttpClient                     : A connection to https://cdn.growthbook.io/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);```

**Comment by vulinh64** [comment]
This PR https://github.com/growthbook/growthbook-sdk-java/pull/43 should have supposedly solve this issue, but for whatever reasons, it was closed. Can we investigate this a little bit further?

**Comment by Bohdan-Kim** [comment]
[The pull request](https://github.com/growthbook/growthbook-sdk-java/pull/98) was created according to this issue.
